### ISSUE TITLE
Can't find file: local.settings.json in the root of the Sketch2Code.Api project.

### ISSUE THREAD

**Issue by quan7794** [Microsoft/AISchoolTutorials#6] opened 2018-11-29 08:28 UTC
As title, your tutorial have some step to modifiy local.settings.json file. But I can't see any file like that. Please upload this file. Thanks so much.

**Comment by gsegares** [comment] 2019-04-01 02:52
Duplicated with [Issue #4](https://github.com/Microsoft/AISchoolTutorials/issues/4), I'll close this one.

**Comment by gsegares** [comment] 2019-04-01 03:01
Duplicate of #4

**Closed** 2019-04-01 18:54 UTC
